# Generated by Django 3.2.1 on 2026-03-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='snapshots/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.CharField(blank=True, max_length=200)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='exams.examsession')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('focus_loss', 'Focus Loss'), ('copy_attempt', 'Copy Attempt'), ('paste_attempt', 'Paste Attempt'), ('right_click', 'Right Click Attempt'), ('fullscreen_exit', 'Fullscreen Exit'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('suspicious_movement', 'Suspicious Movement')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='exams.examsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
