# Generated by Django 3.2.1 on 2026-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='invigilators',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to='accounts.InvigilatorProfile'),
        ),
    ]
